fix: change from yarn to pnpm
due to the error->

Error: EPERM: operation not permitted, unlink 'C:\Users\ianem\projectz\fwk\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node'

successfully created the 'app-one' with pnpm